version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Vite app..."
      - npm run build

artifacts:
  base-directory: dist          # this is Vite's output folder
  files:
    - '**/*'                    # include everything in dist
